language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhmv

matrix:
  allow_failures:
    - php: 5.6
    - php: hhmv

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
