sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/build

language: php

matrix:
  include:
    - php: 5.3
      dist: precise

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - if [[ $TRAVIS_PHP_VERSION != "5.3" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - if [[ $TRAVIS_PHP_VERSION == "5.3" ]]; then make test-coveralls; else make test; fi
