<?php

return array
(
	"search"      => "searches",
	"switch"      => "switches",
	"fix"         => "fixes",
	"box"         => "boxes",
	"process"     => "processes",
	"address"     => "addresses",
	"case"        => "cases",
	"release"     => "releases",
	"stack"       => "stacks",
	"wish"        => "wishes",
	"fish"        => "fish",
	"jeans"       => "jeans",
	"funky jeans" => "funky jeans",
	"my money"    => "my money",

	"category"    => "categories",
	"currency"    => "currencies",
	"energy"      => "energies",
	"query"       => "queries",
	"ability"     => "abilities",
	"agency"      => "agencies",
	"movie"       => "movies",

	"archive"     => "archives",

	"index"       => "indices",

	"wife"        => "wives",
	"safe"        => "saves",
	"half"        => "halves",
	"scarf"       => "scarves",
	"wharf"       => "wharves",

	"move"        => "moves",

	"basis"       => "bases",
	"diagnosis"   => "diagnoses",
	"diagnosis_a" => "diagnosis_as",
	"ellipsis"    => "ellipses",
	"hypothesis"  => "hypotheses",
	"oasis"       => "oases",
	"paralysis"   => "paralyses",
	"synthesis"   => "syntheses",

	"datum"       => "data",
	"medium"      => "media",
	"stadium"     => "stadia",
	"analysis"    => "analyses",
	"my_analysis" => "my_analyses",

	"node_child"  => "node_children",
	"child"       => "children",

	"experience"  => "experiences",
	"experience"  => "experience",
	"day"         => "days",

	"comment"     => "comments",
	"foobar"      => "foobars",
	"newsletter"  => "newsletters",

	"old_news"    => "old_news",
	"news"        => "news",

	"series"      => "series",
	"species"     => "species",

	"quiz"        => "quizzes",

	"perspective" => "perspectives",

	"ox"          => "oxen",
	"photo"       => "photos",
	"buffalo"     => "buffaloes",
	"tomato"      => "tomatoes",
	"potato"      => "potatoes",
	"volcano"     => "volcanoes",
	"hero"        => "heroes",
	"dwarf"       => "dwarves",
	"elf"         => "elves",
	"information" => "information",
	"equipment"   => "equipment",
	"bus"         => "buses",
	"status"      => "statuses",
	"status_code" => "status_codes",
	"mouse"       => "mice",

	"louse"       => "lice",
	"house"       => "houses",
	"virus"       => "viruses",
	"alias"       => "aliases",
	"portfolio"   => "portfolios",

	"vertex"      => "vertices",
	"matrix"      => "matrices",
	"matrix_fu"   => "matrix_fus",

	"axis"        => "axes",
	"taxi"        => "taxis", # prevents regression
	"testis"      => "testes",
	"crisis"      => "crises",

	"rice"        => "rice",
	"shoe"        => "shoes",

	"horse"       => "horses",
	"prize"       => "prizes",
	"edge"        => "edges",

	"cow"         => "cows",
	"database"    => "databases",

	# regression tests against improper inflection regexes
	"|ice"        => "|ices",
	"|ouse"       => "|ouses",
	"slice"       => "slices",
	"police"      => "police",

	# "f" or "fe" => "ves"
	"calf"        => "calves",
	"half"        => "halves",
	"knife"       => "knives",
	"leaf"        => "leaves",
	"life"        => "lives",
	"loaf"        => "loaves",

	# irregulars

	"appendix"    => "appendices",
	"cactus"      => "cacti",
	"child"       => "children",
	"criterion"   => "criteria",
	"curriculum"  => "curricula",
	"foot"        => "feet",
	"genus"       => "genera",
	"goose"       => "geese",
	"is"          => "are",
	"leaf"        => "leaves",
	"loaf"        => "loaves",
	"man"         => "men",
	"move"        => "moves",
	"nucleus"     => "nuclei",
	"octopus"     => "octopuses",
	"person"      => "people",
	"phenomenon"  => "phenomena",
	"radius"      => "radii",
	"salesperson" => "salespeople",
	"sex"         => "sexes",
	"spokesman"   => "spokesmen",
	"stimulus"    => "stimuli",
	"syllabus"    => "syllabi",
	"thief"       => "thieves",
	"tooth"       => "teeth",
	"virus"       => "viruses",
	"was"         => "were",
	"woman"       => "women",
	"zombie"      => "zombies",

	# uncountable

	'advice'      => 'advice',
	'aircraft'    => 'aircraft',
	'art'         => 'art',
	'baggage'     => 'baggage',
	'butter'      => 'butter',
	'clothing'    => 'clothing',
	'coal'        => 'coal',
	'cotton'      => 'cotton',
	'deer'        => 'deer',
	'equipment'   => 'equipment',
	'experience'  => 'experience',
	'feedback'    => 'feedback',
	'fish'        => 'fish',
	'flour'       => 'flour',
	'food'        => 'food',
	'furniture'   => 'furniture',
	'gas'         => 'gas',
	'homework'    => 'homework',
	'impatience'  => 'impatience',
	'information' => 'information',
	'jeans'       => 'jeans',
	'knowledge'   => 'knowledge',
	'leather'     => 'leather',
	'love'        => 'love',
	'luggage'     => 'luggage',
	'management'  => 'management',
	'money'       => 'money',
	'moose'       => 'moose',
	'music'       => 'music',
	'news'        => 'news',
	'oil'         => 'oil',
	'patience'    => 'patience',
	'police'      => 'police',
	'polish'      => 'polish',
	'progress'    => 'progress',
	'research'    => 'research',
	'rice'        => 'rice',
	'salmon'      => 'salmon',
	'sand'        => 'sand',
	'series'      => 'series',
	'sheep'       => 'sheep',
	'silk'        => 'silk',
	'sms'         => 'sms',
	'soap'        => 'soap',
	'spam'        => 'spam',
	'species'     => 'species',
	'staff'       => 'staff',
	'sugar'       => 'sugar',
	'swine'       => 'swine',
	'talent'      => 'talent',
	'toothpaste'  => 'toothpaste',
	'traffic'     => 'traffic',
	'travel'      => 'travel',
	'vinegar'     => 'vinegar',
	'weather'     => 'weather',
	'wood'        => 'wood',
	'wool'        => 'wool',
	'work'        => 'work',
);
